GET http://localhost:8088/?id=99
Accept: application/json

###
GET http://localhost:8088/findEx?flag=true
Accept: application/json

### 超时时间
GET http://localhost:8088/findTimeOut?timeout=2000
Accept: application/json


### 修改grayRatio的值大小
GET http://localhost:8088/updateGrayRatio?grayRatio=100
Accept: application/json
