app:
  id: app1
  namespace: public
  env: dev
hefrpc:
  zkservers: localhost:2181
  zkroot: hefrpc

logging:
  level:
    root: error
    cn.hefrankeleyn.hefrpc: info
    com.hhrpc.hefrpc.demo: info
