server:
  port: 8081

hefrpc:
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      gray: false
      dc: bj
      union: B001
      tc: 25
  zk:
    servers: localhost:2181
    root: hefrpc

hefregistry:
  servers: http://localhost:8383

logging:
  level:
    root: error
    cn.hefrankeleyn.hefrpc.core.registry: debug
    com.hhrpc.hefrpc.demo: info

app:
  id: app01
apollo:
  cluster: default
  cache-dir: /Users/lifei/Documents/opt/data/apollo
  meta: http://localhost:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: false
    namespaces: rpcprovider,application
    eagerLoad:
      enabled: true



