server:
  port: 8081

hefrpc:
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      gray: false
      dc: bj
      union: B001
  zk:
    servers: localhost:2181
    root: hefrpc

logging:
  level:
    root: error
    cn.hefrankeleyn.hefrpc: info
    com.hhrpc.hefrpc.demo: info
