server:
  port: 8088

hefrpc:
  provicer: http://localhost:8081,http://localhost:8082
  zkservers: localhost:2181
  zkroot: hefrpc



app:
  id: app1
  namespace: public
  env: dev
  retries: 2
  timeout: 1
  # 灰度流量百分比（0-100）
  grayRatio: 10

logging:
  level:
    root: error
    cn.hefrankeleyn.hefrpc: info
    com.hhrpc.hefrpc.demo: info